### ISSUE TITLE
mujoco-py dependency while install

### ISSUE THREAD

**Issue by charlesxu90** [brandontrabucco/design-baselines#15]
Dear authors,

Thanks for this nice repository. I'm trying to use this baselines in my experiments. However, I cannot install the version of mujoco-py required.

The error message I met with is as follows. As I'm strictly following the installation procedure. I think this error probably is caused by some outdated dependencies of this repository. I spent a lot of time on this already. But still didn't get a clear clue. Any suggestions are highly appreciated!

```
$ pip install mujoco-py==2.0.2.3 [21:29:14]
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Collecting mujoco-py==2.0.2.3
  Downloading mujoco-py-2.0.2.3.tar.gz (767 kB)
     \u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501 767.5/767.5 kB 2.4 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: glfw>=1.4.0 in /home/user1/miniconda3/envs/design-baselines/lib/python3.7/site-packages (from mujoco-py==2.0.2.3) (2.5.5)
Requirement already satisfied: numpy>=1.11 in /home/user1/miniconda3/envs/design-baselines/lib/python3.7/site-packages (from mujoco-py==2.0.2.3) (1.21.6)
Requirement already satisfied: Cython>=0.27.2 in /home/user1/miniconda3/envs/design-baselines/lib/python3.7/site-packages (from mujoco-py==2.0.2.3) (0.29.32)
Requirement already satisfied: imageio>=2.1.2 in /home/user1/miniconda3/envs/design-baselines/lib/python3.7/site-packages (from mujoco-py==2.0.2.3) (2.22.4)
Requirement already satisfied: cffi>=1.10 in /home/user1/miniconda3/envs/design-baselines/lib/python3.7/site-packages (from mujoco-py==2.0.2.3) (1.15.1)
Requirement already satisfied: lockfile>=0.12.2 in /home/user1/miniconda3/envs/design-baselines/lib/python3.7/site-packages (from mujoco-py==2.0.2.3) (0.12.2)
Requirement already satisfied: pycparser in /home/user1/miniconda3/envs/design-baselines/lib/python3.7/site-packages (from cffi>=1.10->mujoco-py==2.0.2.3) (2.21)
Requirement already satisfied: pillow>=8.3.2 in /home/user1/miniconda3/envs/design-baselines/lib/python3.7/site-packages (from imageio>=2.1.2->mujoco-py==2.0.2.3) (9.3.0)
Building wheels for collected packages: mujoco-py
  Building wheel for mujoco-py (setup.py) ... error
  error: subprocess-exited-with-error
  
  � python setup.py bdist_wheel did not run successfully.
  \u2502 exit code: 1
  \u2570\u2500> [61 lines of output]
      running bdist_wheel
      running build
      
      You appear to be missing MuJoCo.  We expected to find the file here: /home/user1/.mujoco/mujoco200
      
      This package only provides python bindings, the library must be installed separately.
      
      Please follow the instructions on the README to install MuJoCo
      
          https://github.com/openai/mujoco-py#install-mujoco
      
      Which can be downloaded from the website
      
          https://www.roboti.us/index.html
      
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-6251z093/mujoco-py_d42c0775236d4ff3843737ddab1a303c/setup.py", line 45, in <module>
          tests_require=read_requirements_file('requirements.dev.txt'),
        File "/home/user1/miniconda3/envs/design-baselines/lib/python3.7/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "/home/user1/miniconda3/envs/design-baselines/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/home/user1/miniconda3/envs/design-baselines/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/home/user1/miniconda3/envs/design-baselines/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 968, in run_commands
          self.run_command(cmd)
        File "/home/user1/miniconda3/envs/design-baselines/lib/python3.7/site-packages/setuptools/dist.py", line 1217, in run_command
          super().run_command(command)
        File "/home/user1/miniconda3/envs/design-baselines/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
          cmd_obj.run()
        File "/home/user1/miniconda3/envs/design-baselines/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 299, in run
          self.run_command('build')
        File "/home/user1/miniconda3/envs/design-baselines/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 319, in run_command
          self.distribution.run_command(command)
        File "/home/user1/miniconda3/envs/design-baselines/lib/python3.7/site-packages/setuptools/dist.py", line 1217, in run_command
          super().run_command(command)
        File "/home/user1/miniconda3/envs/design-baselines/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
          cmd_obj.run()
        File "/tmp/pip-install-6251z093/mujoco-py_d42c0775236d4ff3843737ddab1a303c/setup.py", line 29, in run
          import mujoco_py  # noqa: force build
        File "/tmp/pip-install-6251z093/mujoco-py_d42c0775236d4ff3843737ddab1a303c/mujoco_py/__init__.py", line 3, in <module>
          from mujoco_py.builder import cymj, ignore_mujoco_warnings, functions, MujocoException
        File "/tmp/pip-install-6251z093/mujoco-py_d42c0775236d4ff3843737ddab1a303c/mujoco_py/builder.py", line 502, in <module>
          mujoco_path, key_path = discover_mujoco()
        File "/tmp/pip-install-6251z093/mujoco-py_d42c0775236d4ff3843737ddab1a303c/mujoco_py/utils.py", line 93, in discover_mujoco
          raise Exception(message)
      Exception:
      You appear to be missing MuJoCo.  We expected to find the file here: /home/user1/.mujoco/mujoco200
      
      This package only provides python bindings, the library must be installed separately.
      
      Please follow the instructions on the README to install MuJoCo
      
          https://github.com/openai/mujoco-py#install-mujoco
      
      Which can be downloaded from the website
      
          https://www.roboti.us/index.html
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for mujoco-py
  Running setup.py clean for mujoco-py
Failed to build mujoco-py
Installing collected packages: mujoco-py
  Attempting uninstall: mujoco-py
    Found existing installation: mujoco-py 2.1.2.14
    Uninstalling mujoco-py-2.1.2.14:
      Successfully uninstalled mujoco-py-2.1.2.14
  Running setup.py install for mujoco-py ... error
  error: subprocess-exited-with-error
  
  � Running setup.py install for mujoco-py did not run successfully.
  \u2502 exit code: 1
  \u2570\u2500> [65 lines of output]
      running install
      /home/user1/miniconda3/envs/design-baselines/lib/python3.7/site-packages/setuptools/command/install.py:37: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        setuptools.SetuptoolsDeprecationWarning,
      running build
      
      You appear to be missing MuJoCo.  We expected to find the file here: /home/user1/.mujoco/mujoco200
      
      This package only provides python bindings, the library must be installed separately.
      
      Please follow the instructions on the README to install MuJoCo
      
          https://github.com/openai/mujoco-py#install-mujoco
      
      Which can be downloaded from the website
      
          https://www.roboti.us/index.html
      
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-6251z093/mujoco-py_d42c0775236d4ff3843737ddab1a303c/setup.py", line 45, in <module>
          tests_require=read_requirements_file('requirements.dev.txt'),
        File "/home/user1/miniconda3/envs/design-baselines/lib/python3.7/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "/home/user1/miniconda3/envs/design-baselines/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/home/user1/miniconda3/envs/design-baselines/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/home/user1/miniconda3/envs/design-baselines/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 968, in run_commands
          self.run_command(cmd)
        File "/home/user1/miniconda3/envs/design-baselines/lib/python3.7/site-packages/setuptools/dist.py", line 1217, in run_command
          super().run_command(command)
        File "/home/user1/miniconda3/envs/design-baselines/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
          cmd_obj.run()
        File "/home/user1/miniconda3/envs/design-baselines/lib/python3.7/site-packages/setuptools/command/install.py", line 68, in run
          return orig.install.run(self)
        File "/home/user1/miniconda3/envs/design-baselines/lib/python3.7/site-packages/setuptools/_distutils/command/install.py", line 698, in run
          self.run_command('build')
        File "/home/user1/miniconda3/envs/design-baselines/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 319, in run_command
          self.distribution.run_command(command)
        File "/home/user1/miniconda3/envs/design-baselines/lib/python3.7/site-packages/setuptools/dist.py", line 1217, in run_command
          super().run_command(command)
        File "/home/user1/miniconda3/envs/design-baselines/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
          cmd_obj.run()
        File "/tmp/pip-install-6251z093/mujoco-py_d42c0775236d4ff3843737ddab1a303c/setup.py", line 29, in run
          import mujoco_py  # noqa: force build
        File "/tmp/pip-install-6251z093/mujoco-py_d42c0775236d4ff3843737ddab1a303c/mujoco_py/__init__.py", line 3, in <module>
          from mujoco_py.builder import cymj, ignore_mujoco_warnings, functions, MujocoException
        File "/tmp/pip-install-6251z093/mujoco-py_d42c0775236d4ff3843737ddab1a303c/mujoco_py/builder.py", line 502, in <module>
          mujoco_path, key_path = discover_mujoco()
        File "/tmp/pip-install-6251z093/mujoco-py_d42c0775236d4ff3843737ddab1a303c/mujoco_py/utils.py", line 93, in discover_mujoco
          raise Exception(message)
      Exception:
      You appear to be missing MuJoCo.  We expected to find the file here: /home/user1/.mujoco/mujoco200
      
      This package only provides python bindings, the library must be installed separately.
      
      Please follow the instructions on the README to install MuJoCo
      
          https://github.com/openai/mujoco-py#install-mujoco
      
      Which can be downloaded from the website
      
          https://www.roboti.us/index.html
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Rolling back uninstall of mujoco-py
  Moving to /home/user1/miniconda3/envs/design-baselines/lib/python3.7/site-packages/mujoco_py-2.1.2.14.dist-info/
   from /home/user1/miniconda3/envs/design-baselines/lib/python3.7/site-packages/~ujoco_py-2.1.2.14.dist-info
  Moving to /home/user1/miniconda3/envs/design-baselines/lib/python3.7/site-packages/mujoco_py/__init__.py
   from /tmp/pip-uninstall-5n3xxpzk/__init__.py
  Moving to /home/user1/miniconda3/envs/design-baselines/lib/python3.7/site-packages/mujoco_py/__pycache__/
   from /home/user1/miniconda3/envs/design-baselines/lib/python3.7/site-packages/mujoco_py/~_pycache__
  Moving to /home/user1/miniconda3/envs/design-baselines/lib/python3.7/site-packages/mujoco_py/builder.py
   from /tmp/pip-uninstall-5n3xxpzk/builder.py
  Moving to /home/user1/miniconda3/envs/design-baselines/lib/python3.7/site-packages/mujoco_py/cymj.c
   from /tmp/pip-uninstall-5n3xxpzk/cymj.c
  Moving to /home/user1/miniconda3/envs/design-baselines/lib/python3.7/site-packages/mujoco_py/cymj.pyx
   from /tmp/pip-uninstall-5n3xxpzk/cymj.pyx
  Moving to /home/user1/miniconda3/envs/design-baselines/lib/python3.7/site-packages/mujoco_py/generated/__init__.py
   from /tmp/pip-uninstall-5n3xxpzk/generated/__init__.py
  Moving to /home/user1/miniconda3/envs/design-baselines/lib/python3.7/site-packages/mujoco_py/generated/__pycache__/
   from /home/user1/miniconda3/envs/design-baselines/lib/python3.7/site-packages/mujoco_py/generated/~_pycache__
  Moving to /home/user1/miniconda3/envs/design-baselines/lib/python3.7/site-packages/mujoco_py/generated/const.py
   from /tmp/pip-uninstall-5n3xxpzk/generated/const.py
  Moving to /home/user1/miniconda3/envs/design-baselines/lib/python3.7/site-packages/mujoco_py/generated/cymj_2.0.2.8_37_macextensionbuilder_37.so
   from /tmp/pip-uninstall-5n3xxpzk/generated/cymj_2.0.2.8_37_macextensionbuilder_37.so
  Moving to /home/user1/miniconda3/envs/design-baselines/lib/python3.7/site-packages/mujoco_py/generated/cymj_2.1.2.14_37_macextensionbuilder_37.so
   from /tmp/pip-uninstall-5n3xxpzk/generated/cymj_2.1.2.14_37_macextensionbuilder_37.so
  Moving to /home/user1/miniconda3/envs/design-baselines/lib/python3.7/site-packages/mujoco_py/generated/wrappers.pxi
   from /tmp/pip-uninstall-5n3xxpzk/generated/wrappers.pxi
  Moving to /home/user1/miniconda3/envs/design-baselines/lib/python3.7/site-packages/mujoco_py/gl/
   from /home/user1/miniconda3/envs/design-baselines/lib/python3.7/site-packages/mujoco_py/~l
  Moving to /home/user1/miniconda3/envs/design-baselines/lib/python3.7/site-packages/mujoco_py/mjbatchrenderer.pyx
   from /tmp/pip-uninstall-5n3xxpzk/mjbatchrenderer.pyx
  Moving to /home/user1/miniconda3/envs/design-baselines/lib/python3.7/site-packages/mujoco_py/mjpid.pyx
   from /tmp/pip-uninstall-5n3xxpzk/mjpid.pyx
  Moving to /home/user1/miniconda3/envs/design-baselines/lib/python3.7/site-packages/mujoco_py/mjrendercontext.pyx
   from /tmp/pip-uninstall-5n3xxpzk/mjrendercontext.pyx
  Moving to /home/user1/miniconda3/envs/design-baselines/lib/python3.7/site-packages/mujoco_py/mjrenderpool.py
   from /tmp/pip-uninstall-5n3xxpzk/mjrenderpool.py
  Moving to /home/user1/miniconda3/envs/design-baselines/lib/python3.7/site-packages/mujoco_py/mjsim.pyx
   from /tmp/pip-uninstall-5n3xxpzk/mjsim.pyx
  Moving to /home/user1/miniconda3/envs/design-baselines/lib/python3.7/site-packages/mujoco_py/mjsimstate.pyx
   from /tmp/pip-uninstall-5n3xxpzk/mjsimstate.pyx
  Moving to /home/user1/miniconda3/envs/design-baselines/lib/python3.7/site-packages/mujoco_py/mjviewer.py
   from /tmp/pip-uninstall-5n3xxpzk/mjviewer.py
  Moving to /home/user1/miniconda3/envs/design-baselines/lib/python3.7/site-packages/mujoco_py/modder.py
   from /tmp/pip-uninstall-5n3xxpzk/modder.py
  Moving to /home/user1/miniconda3/envs/design-baselines/lib/python3.7/site-packages/mujoco_py/opengl_context.pyx
   from /tmp/pip-uninstall-5n3xxpzk/opengl_context.pyx
  Moving to /home/user1/miniconda3/envs/design-baselines/lib/python3.7/site-packages/mujoco_py/pxd/
   from /home/user1/miniconda3/envs/design-baselines/lib/python3.7/site-packages/mujoco_py/~xd
  Moving to /home/user1/miniconda3/envs/design-baselines/lib/python3.7/site-packages/mujoco_py/tests/
   from /home/user1/miniconda3/envs/design-baselines/lib/python3.7/site-packages/mujoco_py/~ests
  Moving to /home/user1/miniconda3/envs/design-baselines/lib/python3.7/site-packages/mujoco_py/utils.py
   from /tmp/pip-uninstall-5n3xxpzk/utils.py
  Moving to /home/user1/miniconda3/envs/design-baselines/lib/python3.7/site-packages/mujoco_py/version.py
   from /tmp/pip-uninstall-5n3xxpzk/version.py
error: legacy-install-failure

� Encountered error while trying to install package.
\u2570\u2500> mujoco-py

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

```

**Comment by charlesxu90** [comment]
BTW, I actually install mujoco-py following the instructions on this repository (https://github.com/openai/mujoco-py#install-mujoco). However, The installed version doesn't match with the required version.

I think the required version might be old. By default, Mujoco and Mujoco-py donot support it now.

**Comment by charlesxu90** [comment]
Finally, I install mujoco-py 2.0.2.3.

- First, I hve to download mujoco200 from here https://www.roboti.us/download.html, and extract it to the suitable location.
- Then I have to install the license from here https://www.roboti.us/file/mjkey.txt
- After that, update the environment `export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/user1/.mujoco/mujoco200/bin`

With the operations above, I was able to install mujoco-py with this command:
```
pip install mujoco-py==2.0.2.3
```
